owner: DELWP-DTV
repo: santa

sites:
- name: Vicmap Property Easements and Road Casements
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Property_Easements_and_Road_Casements/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: Sunshine Activity Centre
  url: https://services7.arcgis.com/fVJQ0uhT9L4zp35f/arcgis/rest/services/ActivityArea_gdb/FeatureServer/0
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: 'Geelong - Weather Station Sensors '
  url: https://www.geelongdataexchange.com.au
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Australian Private Hospitals August 2020
  url: https://services5.arcgis.com/OvOcYIrJnM97ABBA/arcgis/rest/services/Australian_Private_Hospitals_August_2019_WFL1/FeatureServer/0
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Vicmap Vegetation - Tree Extent
  url: https://tiles.arcgis.com/tiles/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Vegetation_Tree_Extent/MapServer?view=wmtsview&cacheKey=95615180464c4085
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: Watercourse Levels
  url: http://www.bom.gov.au/waterdata/services
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: 'Ballarat Council - Air quality '
  url: https://data.ballarat.vic.gov.au
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Vicmap Vegetation - Tree Density
  url: https://tiles.arcgis.com/tiles/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Vegetation_Tree_Density_Tile/MapServer?view=wmtsview&cacheKey=9326ef767e6c9d9c
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: 'Ballarat Council - Temperature Level '
  url: https://data.ballarat.vic.gov.au
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Vicmap Crown Land Tenure
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Crown_Land_Tenure/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: 'Southern Grampians Council - Parking sensors '
  url: https://www.connectgh.com.au
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Vicmap Features of Interest
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Features_of_Interest/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: ABS SEIFA IEO by SA1 2016
  url: https://map.aurin.org.au/geoserver/ows
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Vicmap Position
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Position/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: 2020 NBN Connections by Technology Type
  url: https://programs.communications.gov.au/geoserver/national-broadband-network/wms
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Victorian Land Use Information System 2016-2017
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/DTV/DJPR_Unrestricted/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: ABS SEIFA IER by SA1 2016
  url: https://map.aurin.org.au/geoserver/ows
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Portals
  url: https://terria-catalogs-public.storage.googleapis.com/common/aus-gov-open-data/vic/prod.json
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Education Facilities
  url: https://services.ga.gov.au/gis/rest/services/Foundation_Facilities_Points/MapServer/0
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: Vicmap Planning
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Planning/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: Vicmap Admin
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Admin/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: 'Ballarat Council - Humidity Level '
  url: https://data.ballarat.vic.gov.au
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Watercourse Discharge
  url: http://www.bom.gov.au/waterdata/services
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Geelong - Parking sensors
  url: https://www.geelongdataexchange.com.au
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Vicmap Transport
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Transport/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: Electricity Transmission Lines
  url: https://services.ga.gov.au/gis/rest/services/Foundation_Electricity_Infrastructure/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: Planning scheme zones - Vicmap Planning (PLAN_ZONE)
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Planning/MapServer/3
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: 'Southern Grampians Council - weather-station-status  '
  url: https://www.connectgh.com.au
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Moreland Tree Ledger
  url: https://treeledger.com.au/load_polygon_current
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: City of Melbourne Pedestrian Traffic Counter
  url: https://data.melbourne.vic.gov.au/api/records/1.0/search/?rows=2000&order=DESC&dataset=pedestrian-counting-system-past-hour-counts-per-minute&timezone=Australia%2FSydney&lang=en
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Vicmap Parcel
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Parcel/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: Watercourse Discharge
  url: http://www.bom.gov.au/waterdata/services
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Watercourse Levels
  url: http://www.bom.gov.au/waterdata/services
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Vicmap Property
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Property/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: AURIN
  url: https://map.aurin.org.au/geoserver/ows
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: SHWEP Activity Centre
  url: https://services7.arcgis.com/fVJQ0uhT9L4zp35f/arcgis/rest/services/ActivityArea_gdb/FeatureServer/2
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: ABS SEIFA IRSD by SA1 2016
  url: https://map.aurin.org.au/geoserver/ows
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Southern Grampians Council - Water Levels
  url: https://www.connectgh.com.au
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Vicmap Address
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Address/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: 'Ballarat Council - Noise Observations '
  url: https://data.ballarat.vic.gov.au
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Vicmap Vegetation - Tree Urban
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Vegetation_Tree_Urban/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: Vicmap Geomark
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Geomark/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: ABS SEIFA IRSAD by SA1 2016
  url: https://map.aurin.org.au/geoserver/ows
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Ballarat Council - Noise Sensors
  url: https://data.ballarat.vic.gov.au
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Vicmap Elevation - Statewide (10m to 20m)
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Elevation_STATEWIDE_10_to_20_metre/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: Vicmap Lite
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Lite/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: Vicmap Elevation - Metro (1m to 5m)
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Elevation_METRO_1_to_5_metre/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: Significant Planning Register
  url: https://services7.arcgis.com/fVJQ0uhT9L4zp35f/arcgis/rest/services/SunshineActivityPlanningRegister_250722_gdb/FeatureServer/3
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: 'Ballarat Council - Water Level '
  url: https://data.ballarat.vic.gov.au
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: ACCC Mobile Infrastructure Report 2021
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/DTV/ACCC_Mobile_Infrastructure_Report/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: Australian Public Hospitals 2018-2019
  url: https://services5.arcgis.com/OvOcYIrJnM97ABBA/arcgis/rest/services/Australian_Public_Hospitals_WFL1/FeatureServer/0
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Moreland Tree Ledger - Losses
  url: https://treeledger.com.au/load_polygon_loss
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Vicmap Index
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Index/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: St Albans Activity Centre
  url: https://services7.arcgis.com/fVJQ0uhT9L4zp35f/arcgis/rest/services/ActivityArea_gdb/FeatureServer/1
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Vicmap Hydro
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Hydro/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: Planning scheme overlay - Vicmap Planning (PLAN_OVERLAY)
  url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Planning/MapServer/2
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: local-government-datasets
  url: https://terria-catalogs-public.storage.googleapis.com/common/aus-gov-open-data/vic/prod.json
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Moreland Tree Ledger GeoJson
  url: https://treeledger.com.au/open_leaf/current
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Moreland Tree Ledger - Losses
  url: https://treeledger.com.au/open_leaf/current_loss
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: national-datasets
  url: https://terria-catalogs-public.storage.googleapis.com/nationalmap/prod.json
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Tree Density
  url: https://tiles.arcgis.com/tiles/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Vegetation_Tree_Density/VectorTileServer/tile/{z}/{y}/{x}.pbf
  method: GET
  __dangerous__body_down: Could not access any server machines.
- name: Tree Extent
  url: https://tiles.arcgis.com/tiles/GB33F62SbDxJjwEL/arcgis/rest/services/Vicmap_Vegetation_Tree_Extent/MapServer
  method: POST
  __dangerous__body_down: Could not access any server machines.
- name: Tree Urban
  url: https://dt-geoserver.terria.io/geoserver/vic/wms
  method: GET
  __dangerous__body_down: Could not access any server machines.

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /santa
  logoUrl: https://vic.digitaltwin.terria.io/images/DTV-brand.svg
  name: DTV Santa
  introTitle: "Data Catalogue Uptime Status"
  introMessage: The status page for the Digital Twin Victoria Platform Catalogue. You can use SANTA to automate the process of checking web service endpoints in a catalog. It can analyze the endpoints, test their functionality, and provide valuable insights and reports. SANTA can be a valuable tool for developers and quality assurance teams to ensure the smooth operation of web services in a catalog. Data assets are checked every 12 hours.
  navbar:
    - title: Status
      href: /
    - title: DTV-Platform
      href: https://vic.digitaltwin.terria.io/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
# To change the status check schedule, modify the uptime parameter 
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 9 * * *"


#i18n:
#  footer: [Data attribution](https://www.land.vic.gov.au/maps-and-spatial/digital-twin-victoria/dtv-platform/data-and-terms#heading-4_) | [Terms of Use](https://www.land.vic.gov.au/maps-and-spatial/digital-twin-victoria/dtv-platform/data-and-terms#heading-6) 
