owner: DELWP-DTV
repo: santa

sites:
  - name: Vicmap_Transport
    url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Transport/MapServer
    method: POST
    __dangerous__body_down: "Could not access any server machines. Please contact your system"
    assignees:
      - alex-vic-geo
  - name: esri mapserver non-existant layer test
    url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Transport/MapServer/1234
    method: POST
    __dangerous__body_down: "Could not access any server machines. Please contact your system"
    assignees:
      - alex-vic-geo
  - name: Vicmap_Transport Road Layer 1
    url: https://enterprise.mapshare.vic.gov.au/server/rest/services/Vicmap_Transport/MapServer/1
    method: POST
    __dangerous__body_down: "Could not access any server machines. Please contact your system"
    assignees:
      - alex-vic-geo
  - name: Sunshine Activity Centre
    url: https://services7.arcgis.com/fVJQ0uhT9L4zp35f/arcgis/rest/services/ActivityArea_gdb/FeatureServer/0
    method: POST
    __dangerous__body_down: "Could not access any server machines. Please contact your system"
    assignees: alex-vic-geo

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /santa
  logoUrl: https://vic.digitaltwin.terria.io/images/DTV-brand.svg
  name: DTV Santa
  introTitle: "Data Catalogue Uptime Status"
  introMessage: The status page for the Digital Twin Victoria Platform Catalogue. Data assets are checked every 12 hours.
  navbar:
    - title: Status
      href: /
    - title: DTV-Platform
      href: https://vic.digitaltwin.terria.io/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
# To change the status check schedule, modify the uptime parameter 
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "1 */6 * * *"


#i18n:
#  footer: [Data attribution](https://www.land.vic.gov.au/maps-and-spatial/digital-twin-victoria/dtv-platform/data-and-terms#heading-4_) | [Terms of Use](https://www.land.vic.gov.au/maps-and-spatial/digital-twin-victoria/dtv-platform/data-and-terms#heading-6) 
